language: ruby
rvm:
  - "2.0.0"
  - "1.9.3"
before_script:
  - psql -c 'create database RaishopDB_test;' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
