development:
  adapter: postgresql
  database: RaishopDB
  pool: 5
  timeout: 5000
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: RaishopDB_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres

production:
  adapter: postgresql
  database: RaishopPROD
  timeout: 5000
